[profile.release]
panic = 'unwind'

[workspace]
resolver = "2"

members = [
    'node',
    'runtime',
    'multi-pow',
]

exclude = [
    "contracts/roulette",
    "contracts/psp22-traits",
    "contracts/psp22",
    "contracts/simple-dex",
    "contracts/old_a",
    "contracts/new_a",
    "contracts/test-utils",
]