[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2021'
name = 'utxo-workshop'
repository = 'https://github.com/substrate-developer-hub/utxo-workshop'
version = '3.0.0'

[build-dependencies]
#TODO Do we still need this?
#substrate-build-script-utils = '2.0.0-rc6'

[dependencies.utxo-runtime]
path = '../runtime'
version = '3.0.0'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'
parity-scale-codec = '3.1.2'
#TODO
sha3 = "0.8"
rand = { version = "0.7", features = ["small_rng"] }

sc-consensus-pow = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sc-basic-authorship = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sc-cli = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sc-client-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sc-consensus = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sc-executor = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sc-network = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sc-service = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sc-transaction-pool = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-blockchain = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-consensus = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-consensus-pow = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-core = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-inherents = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-runtime = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-timestamp = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sp-transaction-pool = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }
sha3pow = {path = './sha3pow'}
hex = "0.4"

[[bin]]
name = 'utxo-workshop'
