[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2021'
name = 'academy-pow'
version = '3.0.0'

[build-dependencies]
substrate-build-script-utils = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }

[dependencies.academy-pow-runtime]
path = '../runtime'
version = '3.0.0'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
clap = { version = "3.1.6", features = ["derive"] }
parity-scale-codec = '3.1.2'
sha3 = "0.10.1"
rand = { version = "0.8.5", features = ["small_rng"] }
jsonrpsee = { version = "0.13.0", features = ["server"] }

sc-consensus-pow = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sc-basic-authorship = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sc-cli = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24", features = ["wasmtime"] }
sc-client-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sc-consensus = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sc-executor = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24", features = ["wasmtime"] }
sc-network = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sc-service = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24", features = ["wasmtime"] }
sc-telemetry = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sc-transaction-pool = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-blockchain = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-consensus = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-consensus-pow = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-core = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-inherents = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-runtime = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-timestamp = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sp-transaction-pool = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.24" }
sha3pow = {path = './sha3pow'}
hex = "0.4"

[[bin]]
name = 'academy-pow'
